
# env SYNAPSE_ID=X..1 SYNAPSE_INSTANCES=1 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=X..2 SYNAPSE_INSTANCES=2 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=X..3 SYNAPSE_INSTANCES=3 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=X..4 SYNAPSE_INSTANCES=4 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
#
# env SYNAPSE_ID=C0.1 SYNAPSE_INSTANCES=1 SYNAPSE_COMPUTE_GFLOPS=0000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=C0.2 SYNAPSE_INSTANCES=2 SYNAPSE_COMPUTE_GFLOPS=0000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=C0.3 SYNAPSE_INSTANCES=3 SYNAPSE_COMPUTE_GFLOPS=0000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=C0.4 SYNAPSE_INSTANCES=4 SYNAPSE_COMPUTE_GFLOPS=0000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# 
# env SYNAPSE_ID=C1.1 SYNAPSE_INSTANCES=1 SYNAPSE_COMPUTE_GFLOPS=1000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=C1.2 SYNAPSE_INSTANCES=2 SYNAPSE_COMPUTE_GFLOPS=1000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=C1.3 SYNAPSE_INSTANCES=3 SYNAPSE_COMPUTE_GFLOPS=1000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=C1.4 SYNAPSE_INSTANCES=4 SYNAPSE_COMPUTE_GFLOPS=1000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# 
# env SYNAPSE_ID=C2.1 SYNAPSE_INSTANCES=1 SYNAPSE_COMPUTE_GFLOPS=2000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=C2.2 SYNAPSE_INSTANCES=2 SYNAPSE_COMPUTE_GFLOPS=2000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=C2.3 SYNAPSE_INSTANCES=3 SYNAPSE_COMPUTE_GFLOPS=2000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=C2.4 SYNAPSE_INSTANCES=4 SYNAPSE_COMPUTE_GFLOPS=2000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# 
# env SYNAPSE_ID=C3.1 SYNAPSE_INSTANCES=1 SYNAPSE_COMPUTE_GFLOPS=3000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=C3.2 SYNAPSE_INSTANCES=2 SYNAPSE_COMPUTE_GFLOPS=3000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=C3.3 SYNAPSE_INSTANCES=3 SYNAPSE_COMPUTE_GFLOPS=3000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=C3.4 SYNAPSE_INSTANCES=4 SYNAPSE_COMPUTE_GFLOPS=3000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# 
# env SYNAPSE_ID=C4.1 SYNAPSE_INSTANCES=1 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=C4.2 SYNAPSE_INSTANCES=2 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=C4.3 SYNAPSE_INSTANCES=3 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=C4.4 SYNAPSE_INSTANCES=4 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# 
# env SYNAPSE_ID=C5.1 SYNAPSE_INSTANCES=1 SYNAPSE_COMPUTE_GFLOPS=5000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=C5.2 SYNAPSE_INSTANCES=2 SYNAPSE_COMPUTE_GFLOPS=5000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=C5.3 SYNAPSE_INSTANCES=3 SYNAPSE_COMPUTE_GFLOPS=5000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=C5.4 SYNAPSE_INSTANCES=4 SYNAPSE_COMPUTE_GFLOPS=5000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# 
# env SYNAPSE_ID=C6.1 SYNAPSE_INSTANCES=1 SYNAPSE_COMPUTE_GFLOPS=6000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=C6.2 SYNAPSE_INSTANCES=2 SYNAPSE_COMPUTE_GFLOPS=6000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=C6.3 SYNAPSE_INSTANCES=3 SYNAPSE_COMPUTE_GFLOPS=6000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=C6.4 SYNAPSE_INSTANCES=4 SYNAPSE_COMPUTE_GFLOPS=6000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# 
# env SYNAPSE_ID=C7.1 SYNAPSE_INSTANCES=1 SYNAPSE_COMPUTE_GFLOPS=7000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=C7.2 SYNAPSE_INSTANCES=2 SYNAPSE_COMPUTE_GFLOPS=7000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=C7.3 SYNAPSE_INSTANCES=3 SYNAPSE_COMPUTE_GFLOPS=7000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=C7.4 SYNAPSE_INSTANCES=4 SYNAPSE_COMPUTE_GFLOPS=7000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# 
# env SYNAPSE_ID=C8.1 SYNAPSE_INSTANCES=1 SYNAPSE_COMPUTE_GFLOPS=8000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=C8.2 SYNAPSE_INSTANCES=2 SYNAPSE_COMPUTE_GFLOPS=8000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=C8.3 SYNAPSE_INSTANCES=3 SYNAPSE_COMPUTE_GFLOPS=8000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=C8.4 SYNAPSE_INSTANCES=4 SYNAPSE_COMPUTE_GFLOPS=8000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# 
# 
#
# env SYNAPSE_ID=M0.1 SYNAPSE_INSTANCES=1 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=M0.2 SYNAPSE_INSTANCES=2 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=M0.3 SYNAPSE_INSTANCES=3 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=M0.4 SYNAPSE_INSTANCES=4 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
#
# env SYNAPSE_ID=M1.1 SYNAPSE_INSTANCES=1 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=1000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=M1.2 SYNAPSE_INSTANCES=2 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=1000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=M1.3 SYNAPSE_INSTANCES=3 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=1000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=M1.4 SYNAPSE_INSTANCES=4 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=1000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
#
# env SYNAPSE_ID=M2.1 SYNAPSE_INSTANCES=1 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=2000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=M2.2 SYNAPSE_INSTANCES=2 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=2000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=M2.3 SYNAPSE_INSTANCES=3 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=2000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=M2.4 SYNAPSE_INSTANCES=4 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=2000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
#
# env SYNAPSE_ID=M3.1 SYNAPSE_INSTANCES=1 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=3000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=M3.2 SYNAPSE_INSTANCES=2 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=3000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=M3.3 SYNAPSE_INSTANCES=3 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=3000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=M3.4 SYNAPSE_INSTANCES=4 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=3000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
#
# env SYNAPSE_ID=M4.1 SYNAPSE_INSTANCES=1 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=M4.2 SYNAPSE_INSTANCES=2 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=M4.3 SYNAPSE_INSTANCES=3 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=M4.4 SYNAPSE_INSTANCES=4 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
#
# env SYNAPSE_ID=M5.1 SYNAPSE_INSTANCES=1 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=5000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=M5.2 SYNAPSE_INSTANCES=2 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=5000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=M5.3 SYNAPSE_INSTANCES=3 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=5000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
##env SYNAPSE_ID=M5.4 SYNAPSE_INSTANCES=4 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=5000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
#
# env SYNAPSE_ID=M6.1 SYNAPSE_INSTANCES=1 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=6000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=M6.2 SYNAPSE_INSTANCES=2 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=6000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
##env SYNAPSE_ID=M6.3 SYNAPSE_INSTANCES=3 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=6000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
##env SYNAPSE_ID=M6.4 SYNAPSE_INSTANCES=4 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=6000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
#
# env SYNAPSE_ID=M7.1 SYNAPSE_INSTANCES=1 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=7000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=M7.2 SYNAPSE_INSTANCES=2 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=7000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
##env SYNAPSE_ID=M7.3 SYNAPSE_INSTANCES=3 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=7000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
##env SYNAPSE_ID=M7.4 SYNAPSE_INSTANCES=4 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=7000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
#
# env SYNAPSE_ID=M8.1 SYNAPSE_INSTANCES=1 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=8000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=M8.2 SYNAPSE_INSTANCES=2 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=8000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
##env SYNAPSE_ID=M8.3 SYNAPSE_INSTANCES=3 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=8000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
##env SYNAPSE_ID=M8.4 SYNAPSE_INSTANCES=4 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=8000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
#
#
#
# env SYNAPSE_ID=S0.1 SYNAPSE_INSTANCES=1 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=S0.2 SYNAPSE_INSTANCES=2 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=S0.3 SYNAPSE_INSTANCES=3 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=S0.4 SYNAPSE_INSTANCES=4 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
#
# env SYNAPSE_ID=S1.1 SYNAPSE_INSTANCES=1 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=S1.2 SYNAPSE_INSTANCES=2 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=S1.3 SYNAPSE_INSTANCES=3 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
# env SYNAPSE_ID=S1.4 SYNAPSE_INSTANCES=4 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=1000 python $HOME/synapse/test.py
#
# env SYNAPSE_ID=S2.1 SYNAPSE_INSTANCES=1 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=2000 python $HOME/synapse/test.py
# env SYNAPSE_ID=S2.2 SYNAPSE_INSTANCES=2 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=2000 python $HOME/synapse/test.py
# env SYNAPSE_ID=S2.3 SYNAPSE_INSTANCES=3 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=2000 python $HOME/synapse/test.py
# env SYNAPSE_ID=S2.4 SYNAPSE_INSTANCES=4 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=2000 python $HOME/synapse/test.py
#
# env SYNAPSE_ID=S3.1 SYNAPSE_INSTANCES=1 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=3000 python $HOME/synapse/test.py
# env SYNAPSE_ID=S3.2 SYNAPSE_INSTANCES=2 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=3000 python $HOME/synapse/test.py
# env SYNAPSE_ID=S3.3 SYNAPSE_INSTANCES=3 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=3000 python $HOME/synapse/test.py
# env SYNAPSE_ID=S3.4 SYNAPSE_INSTANCES=4 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=3000 python $HOME/synapse/test.py
#
# env SYNAPSE_ID=S4.1 SYNAPSE_INSTANCES=1 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=4000 python $HOME/synapse/test.py
# env SYNAPSE_ID=S4.2 SYNAPSE_INSTANCES=2 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=4000 python $HOME/synapse/test.py
# env SYNAPSE_ID=S4.3 SYNAPSE_INSTANCES=3 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=4000 python $HOME/synapse/test.py
# env SYNAPSE_ID=S4.4 SYNAPSE_INSTANCES=4 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=4000 python $HOME/synapse/test.py
#
# env SYNAPSE_ID=S5.1 SYNAPSE_INSTANCES=1 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=5000 python $HOME/synapse/test.py
# env SYNAPSE_ID=S5.2 SYNAPSE_INSTANCES=2 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=5000 python $HOME/synapse/test.py
# env SYNAPSE_ID=S5.3 SYNAPSE_INSTANCES=3 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=5000 python $HOME/synapse/test.py
# env SYNAPSE_ID=S5.4 SYNAPSE_INSTANCES=4 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=5000 python $HOME/synapse/test.py
#
# env SYNAPSE_ID=S6.1 SYNAPSE_INSTANCES=1 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=6000 python $HOME/synapse/test.py
# env SYNAPSE_ID=S6.2 SYNAPSE_INSTANCES=2 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=6000 python $HOME/synapse/test.py
# env SYNAPSE_ID=S6.3 SYNAPSE_INSTANCES=3 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=6000 python $HOME/synapse/test.py
# env SYNAPSE_ID=S6.4 SYNAPSE_INSTANCES=4 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=6000 python $HOME/synapse/test.py
#
# env SYNAPSE_ID=S7.1 SYNAPSE_INSTANCES=1 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=7000 python $HOME/synapse/test.py
# env SYNAPSE_ID=S7.2 SYNAPSE_INSTANCES=2 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=7000 python $HOME/synapse/test.py
# env SYNAPSE_ID=S7.3 SYNAPSE_INSTANCES=3 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=7000 python $HOME/synapse/test.py
# env SYNAPSE_ID=S7.4 SYNAPSE_INSTANCES=4 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=7000 python $HOME/synapse/test.py
#
# env SYNAPSE_ID=S8.1 SYNAPSE_INSTANCES=1 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=8000 python $HOME/synapse/test.py
# env SYNAPSE_ID=S8.2 SYNAPSE_INSTANCES=2 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=8000 python $HOME/synapse/test.py
# env SYNAPSE_ID=S8.3 SYNAPSE_INSTANCES=3 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=8000 python $HOME/synapse/test.py
# env SYNAPSE_ID=S8.4 SYNAPSE_INSTANCES=4 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=4000 SYNAPSE_STORAGE_GBYTES=8000 python $HOME/synapse/test.py
 
# env SYNAPSE_ID=YC.01 SYNAPSE_INSTANCES=01 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.02 SYNAPSE_INSTANCES=02 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.03 SYNAPSE_INSTANCES=03 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.04 SYNAPSE_INSTANCES=04 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.05 SYNAPSE_INSTANCES=05 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.06 SYNAPSE_INSTANCES=06 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.07 SYNAPSE_INSTANCES=07 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.08 SYNAPSE_INSTANCES=08 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.09 SYNAPSE_INSTANCES=09 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.10 SYNAPSE_INSTANCES=10 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.11 SYNAPSE_INSTANCES=11 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.12 SYNAPSE_INSTANCES=12 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.13 SYNAPSE_INSTANCES=13 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.14 SYNAPSE_INSTANCES=14 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.15 SYNAPSE_INSTANCES=15 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.16 SYNAPSE_INSTANCES=16 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.17 SYNAPSE_INSTANCES=17 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.18 SYNAPSE_INSTANCES=18 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.19 SYNAPSE_INSTANCES=19 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.20 SYNAPSE_INSTANCES=20 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.21 SYNAPSE_INSTANCES=21 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.22 SYNAPSE_INSTANCES=22 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.23 SYNAPSE_INSTANCES=23 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.24 SYNAPSE_INSTANCES=24 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.25 SYNAPSE_INSTANCES=25 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.26 SYNAPSE_INSTANCES=26 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.27 SYNAPSE_INSTANCES=27 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.28 SYNAPSE_INSTANCES=28 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.29 SYNAPSE_INSTANCES=29 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.30 SYNAPSE_INSTANCES=30 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.31 SYNAPSE_INSTANCES=31 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.32 SYNAPSE_INSTANCES=32 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.33 SYNAPSE_INSTANCES=33 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.34 SYNAPSE_INSTANCES=34 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.35 SYNAPSE_INSTANCES=35 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.36 SYNAPSE_INSTANCES=36 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.37 SYNAPSE_INSTANCES=37 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.38 SYNAPSE_INSTANCES=38 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.39 SYNAPSE_INSTANCES=39 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.40 SYNAPSE_INSTANCES=40 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.41 SYNAPSE_INSTANCES=41 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.42 SYNAPSE_INSTANCES=42 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.43 SYNAPSE_INSTANCES=43 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.44 SYNAPSE_INSTANCES=44 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.45 SYNAPSE_INSTANCES=45 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.46 SYNAPSE_INSTANCES=46 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.47 SYNAPSE_INSTANCES=47 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.48 SYNAPSE_INSTANCES=48 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.49 SYNAPSE_INSTANCES=49 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.50 SYNAPSE_INSTANCES=50 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.51 SYNAPSE_INSTANCES=51 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.52 SYNAPSE_INSTANCES=52 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.53 SYNAPSE_INSTANCES=53 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.54 SYNAPSE_INSTANCES=54 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.55 SYNAPSE_INSTANCES=55 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.56 SYNAPSE_INSTANCES=56 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.57 SYNAPSE_INSTANCES=57 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.58 SYNAPSE_INSTANCES=58 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.59 SYNAPSE_INSTANCES=59 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.60 SYNAPSE_INSTANCES=60 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.61 SYNAPSE_INSTANCES=61 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.62 SYNAPSE_INSTANCES=62 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
# env SYNAPSE_ID=YC.63 SYNAPSE_INSTANCES=63 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py
  env SYNAPSE_ID=YC.64 SYNAPSE_INSTANCES=64 SYNAPSE_COMPUTE_GFLOPS=4000 SYNAPSE_MEMORY_GBYTES=0000 SYNAPSE_STORAGE_GBYTES=0000 python $HOME/synapse/test.py

